// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Todo struct {
	ID          uuid.UUID
	Title       string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Name      string
	Username  string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}
