services:
  postgres_db:
    image: postgres:12-alpine
    ports: -"5040:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
  go-api:
    build: ./
    ports: -8000:8000
    env_file:
      - .env
volumes:
  pg-data:
